# Generated by Django 5.2.7 on 2025-10-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='negocio_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocio', to='negocios.negocios'),
        ),
        migrations.AddField(
            model_name='alertas',
            name='producto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='inventario.productos'),
        ),
    ]
