# Generated by Django 5.2.7 on 2025-10-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
        ('negocios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='negocio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocio', to='negocios.negocios'),
        ),
    ]
