# Generated by Django 5.2.7 on 2025-10-21 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='negocio_id',
            new_name='negocio',
        ),
    ]
