# Generated by Django 5.2.7 on 2025-10-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_negocio_id_clientes_negocio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='negocio',
        ),
    ]
