# Generated by Django 5.2.7 on 2025-10-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.IntegerField(null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField()),
                ('fecha_limite_pago', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_pago', models.DateTimeField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcialmente pagado'), ('completo', 'Pagado completo'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('monto', models.IntegerField()),
                ('mensaje_bloqueo', models.TextField()),
            ],
        ),
    ]
